apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ibonjour123456-0013e-certificate
  namespace: ibonjour123456-0013e
spec:
  secretName: ibonjour123456-0013e-secret-tls
  commonName: ronaldo123-ibonjour123456.assessify.org
  dnsNames:
  - ronaldo123-ibonjour123456.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
